export { default as ReactIcon } from "./img/svg/React.svg";
export { default as ReactIconStroke } from "./img/svg/WhiteStrokeLogos/React.svg";
export { default as ExpressIcon } from "./img/svg/express.svg";
export { default as ExpressIconStroke } from "./img/svg/WhiteStrokeLogos/express.svg";
export { default as MongoDBIcon } from "./img/svg/MongoDB.svg";
export { default as MongoDBIconStroke } from "./img/svg/WhiteStrokeLogos/MongoDB.svg";
export { default as NodeJSIcon } from "./img/svg/nodejs.svg";
export { default as NodeJSIconStroke } from "./img/svg/WhiteStrokeLogos/nodejs.svg";
export { default as PlaceHolderPic } from "./img/Placeholder.png";
export { default as HTML } from "./img/svg/HTML.svg";
export { default as HTMLStroke } from "./img/svg/WhiteStrokeLogos/HTML.svg";
export { default as CSS } from "./img/svg/CSS.svg";
export { default as CSSStroke } from "./img/svg/WhiteStrokeLogos/CSS.svg";
export { default as JavaScript } from "./img/svg/Javascript.svg";
export { default as JavaScriptStroke } from "./img/svg/WhiteStrokeLogos/Javascript.svg";
export { default as MovieMania1 } from "./img/MovieMania1.webp";
export { default as PokeDex } from "./img/PokeDex.webp";
export { default as WeatherApp } from "./img/WeatherApp.png";
export { default as SilentMoon } from "./img/SilentMoonImg.png"
export { default as Redux } from "./img/svg/redux.svg"
export { default as ReduxStroke } from "./img/svg/WhiteStrokeLogos/redux.svg"
export { default as Firebase } from "./img/svg/Firebase.svg"
export { default as Git } from "./img/svg/Git.svg"
export { default as Figma } from "./img/svg/Figma.svg"
export { default as FigmaStroke } from "./img/svg/WhiteStrokeLogos/Figma.svg"
export { default as Sass } from "./img/svg/Sass.svg"
export { default as Bootstrap } from "./img/svg/Bootstrap_.svg"
export { default as TS } from "./img/svg/TS.svg"
export { default as TSStroke } from "./img/svg/WhiteStrokeLogos/Typescript.svg"
export const aosDataProject = { "data-aos": "zoom-out", "data-aos-offset": "140" };
export const aosDataTechStack = { "ata-aos": "zoom-out", "data-aos-easing": "ease-in-out" };
